name: AutoDoc
version: 2015.04.29
date: 29/04/2015
description: Generate documentation from GAP source code

authors:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math

maintainers:
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Max Horn
      url: http://www.quendi.de/math

GAP: ">= 4.5"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://wwwb.math.rwth-aachen.de/~gutsche/gap_packages/AutoDoc
readme: http://wwwb.math.rwth-aachen.de/~gutsche/gap_packages/AutoDoc/README.AutoDoc
packageinfo: http://wwwb.math.rwth-aachen.de/~gutsche/gap_packages/AutoDoc/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://wwwb.math.rwth-aachen.de/~gutsche/gap_packages/AutoDoc/AutoDoc-2015.04.29.tar.gz

abstract: 

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
